tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG
    before: |
      cd $THEIA_WORKSPACE_ROOT
      chmod u+x bin/*
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli.sh
      source ./bin/generate_tfrc_credentials
      cp $$THEIA_WORKSPACE_ROOT/terraform.tfvars.example $$THEIA_WORKSPACE_ROOT/terraform.tfvars
      source ~/.bash_profile
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $THEIA_WORKSPACE_ROOT
      source ./bin/install_aws_cli.sh
      source ~/.bash_profile
  - name: http-server
    before: |
      npm install --global http-server
    command: 
      http-server
  - name: sinatra
    before: | 
      cd $THEIA_WORKSPACE_ROOT/terratowns_mock_server
      chmod u+x bin/*
      bundle install
      bundle exec ruby server.rb 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform